SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[newview]'
GO
DROP VIEW [dbo].[newview]
GO
PRINT N'Creating [dbo].[oldview]'
GO
CREATE proc [dbo].[oldview]
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
    SELECT 'Hi'
-- WITH CHECK OPTION
GO
